language: python
services:
- docker
python:
- '3.6'
install:
- make deps
script:
- make docker_build
- make docker_push
deploy:
  provider: heroku
  app: testowa-apka99
  api_key:
    secure: Oq+Q400bnYOmLDY9rlvqKnNBe4BdCGeMIdbkCaKMvmihzpJ+HkP2eS14TTQ3yGmL2ZuPH+Y3F3aioi6QWLRREpFDAH4X6HaVyyzfS+FyOA0Z4l4uyiv03po4vi1w+IP0qieNhoEK5+iJiJRjFmXvZOc+/TaPUUjvzd0ef4fYaZeKLCsd5vPb+wBLzEt2oBAg/nHrVPsWm/Ioq8OcSjSZfoiAq/Rhj8rMC8V8x+aK/yJa3IN3gh6YpP5LhHxTTb2fZb+3iIjhEu9I6Gv56axNTef5EjEMVZD8ivDBf5Ph6hzm5szKUt2LgKHaqjKo4W0TDiopnUC03gmeETd3Bf8idUjZDm7hU6c0bZxy8mLcvcxXVcWZuBLrGjmD46APy7cx3rj8QONDCIIH+IQDxJO4Pu08YmPTytKdKKLsV+47F5rpjocMjKwSDjlE03K8kJK8Kox2hcKPjrIFB3IJqABzlCvifd31iGzHnxVzKFUZgXWhN/awvTLGcpB69z+yGON6IHnkSeZB33aHcKsj4jWwHgRyt6G6slVQI415vpIlNW0NVX3fnlBV2DwUfyVRKNlu9ivCiYTHMZqTqtGFApBYADGyY8bACns7w9SeEnQRZUcZTNkwX/5vSC/bBjAocNv0SsbGAa/oJYQbisFStEp94c/TY16T/I6KN2lS6ZsU+jk=
