language: python
services:
        - docker
python:
        - "3.6"
install:
        - make deps
script:
        - make docker_build
        - make docker_push

deploy:
    provider: heroku
    app: testowa-apka99
    api_key: ${HEROKU_API_KEY}
